Repository git-chglog/git-chglog, pull requests merged in 2018-02, with the labels that each got.

#5 Release flow & Fix testing
  chglog_test.go
  scripts/release.sh
  tag_reader.go
Labels: type: bug, type: enhancement

#4 fix a small typo, no content changes
  README.md
Labels: type: documentation

#6 Coverage measurement
  .travis.yml
  README.md
Labels: type: enhancement, type: refactoring

#8 v0.0.3
  Makefile
  cmd/git-chglog/builder.go
  cmd/git-chglog/cli.go
  cmd/git-chglog/cli_test.go
  cmd/git-chglog/config.go
  cmd/git-chglog/config_builder.go
  cmd/git-chglog/config_builder_mock.go
  cmd/git-chglog/config_builder_test.go
  cmd/git-chglog/config_test.go
  cmd/git-chglog/context.go
  cmd/git-chglog/fs.go
  cmd/git-chglog/fs_mock.go
  cmd/git-chglog/initializer.go
  cmd/git-chglog/initializer_test.go
  cmd/git-chglog/main.go
  cmd/git-chglog/questioner.go
  cmd/git-chglog/questioner_mock.go
  cmd/git-chglog/template_builder.go
  cmd/git-chglog/template_builder_mock.go
  cmd/git-chglog/template_builder_test.go
  cmd/git-chglog/variables.go
  cmd/git-chglog/variables_test.go
  fields.go
  processor.go
  processor_test.go
  tag_reader.go
  tag_reader_test.go
Labels: type: enhancement, type: feature, type: refactoring

#9 support Windows colors
  cmd/git-chglog/main.go
Labels: type: bug, type: enhancement

#10 some fixes of tests on Windows
  cmd/git-chglog/cli_test.go
  cmd/git-chglog/config_test.go
Labels: type: bug, type: refactoring
