Repository git-chglog/git-chglog, pull requests merged in 2018-03, with the labels that each got.

#11 New template and pass all the test cases with windows! and usability update.
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  cmd/git-chglog/config_test.go
  cmd/git-chglog/custom_template_builder.go
  cmd/git-chglog/custom_template_builder_test.go
  cmd/git-chglog/initializer.go
  cmd/git-chglog/initializer_test.go
  cmd/git-chglog/kac_template_builder.go
  cmd/git-chglog/kac_template_builder_test.go
  cmd/git-chglog/main.go
  cmd/git-chglog/template_builder.go
  cmd/git-chglog/variables.go
  scripts/release.sh
  vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
  vendor/gopkg.in/AlecAivazis/survey.v1/select.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/LICENSE.txt
  vendor/gopkg.in/AlecAivazis/survey.v1/validate.go
Labels: type: bug, type: feature, type: refactoring

#12 Add support for GitLab
  Makefile
  README.md
  cmd/git-chglog/config.go
  cmd/git-chglog/custom_template_builder.go
  cmd/git-chglog/kac_template_builder.go
  cmd/git-chglog/processor_factory.go
  cmd/git-chglog/processor_factory_test.go
  cmd/git-chglog/variables.go
  processor.go
  processor_test.go
Labels: type: enhancement, type: feature

#13 Fix preview string of commit subject
  cmd/git-chglog/variables.go
Labels: type: bug
