Repository git-chglog/git-chglog, pull requests merged in 2021-03, with the labels that each got.

#102 chore(deps): add initial renovatebot configuration
  .github/renovate.json
Labels: dependencies

#108 fix(deps): update module gopkg.in/alecaivazis/survey.v1 to github.com/AlecAivazis/survey/v2
  cmd/git-chglog/questioner.go
  go.mod
  go.sum
Labels: dependencies, major

#107 fix(deps): update module github.com/urfave/cli to v2
  cmd/git-chglog/main.go
  cmd/git-chglog/main_test.go
  go.mod
  go.sum
Labels: dependencies, major

#109 fix(deps): update module gopkg.in/kyokomi/emoji.v1 to github.com/kyokomi/emoji/v2
  cmd/git-chglog/logger.go
  cmd/git-chglog/logger_test.go
  go.mod
  go.sum
Labels: dependencies, major

#113 fix(init): support OptionAnswer form in survey/v2
  cmd/git-chglog/questioner.go
Labels: type: bug

#117 fix(short flags): correctly define cli flags with shorthands
  cmd/git-chglog/main.go
Labels: type: bug

#120 chore(ci): add golangci-lint action and apply linting changes
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  README.md
  chglog.go
  chglog_test.go
  cmd/git-chglog/cli.go
  cmd/git-chglog/cli_test.go
  cmd/git-chglog/config.go
  cmd/git-chglog/config_loader.go
  cmd/git-chglog/context.go
  cmd/git-chglog/custom_template_builder.go
  cmd/git-chglog/initializer.go
  cmd/git-chglog/main.go
  cmd/git-chglog/main_test.go
  cmd/git-chglog/processor_factory_test.go
  cmd/git-chglog/questioner.go
  cmd/git-chglog/utils.go
  cmd/git-chglog/variables.go
  commit_extractor.go
  commit_extractor_test.go
  commit_filter.go
  commit_filter_test.go
  commit_parser.go
  commit_parser_test.go
  example_test.go
  fields.go
  jira.go
  jira_test.go
  logger.go
  logger_test.go
  processor.go
  processor_test.go
  tag_reader.go
  tag_reader_test.go
  tag_selector.go
  tag_selector_test.go
Labels: type: breaking change, type: refactoring

#124 feat: allow tag sorting by semver
  README.md
  chglog.go
  chglog_test.go
  cmd/git-chglog/config.go
  go.mod
  go.sum
  tag_reader.go
  tag_reader_test.go
Labels: type: enhancement

#121 feat: add support for rendering .Body after .Subject as part of list
  chglog.go
  chglog_test.go
  commit_parser.go
  commit_parser_test.go
  fields.go
  testdata/trimmed_body.md
Labels: type: enhancement

#127 chore: use ldflags to pass version to build process
  Makefile
  cmd/git-chglog/main.go
  cmd/git-chglog/version.go
Labels: type: refactoring

#129 chore(CHANGELOG): regenerate CHANGELOG with type-scope and KAC template
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  CHANGELOG.md
  Makefile
Labels: type: bug, type: documentation

#131 feat: add sprig support...continued
  README.md
  chglog.go
  chglog_test.go
  go.mod
  go.sum
  testdata/with_sprig.md
Labels: type: feature

#130 chore: add make release target
  Makefile
  README.md
Labels: type: enhancement
